# Lang
language: en

# Header
menu:
  Home: /
  Archives: /blog
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics: UA-89176659-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: John Stewart
description: MLB Advanced Media Software Engineer. Convinced I was put on this planet to eat tacos and occasionally build things.
links:
  Blog: /blog
  GitHub: https://github.com/johnstew
  Twitter: http://twitter.com/j0hnstew
  Codepen: http://codepen.io/johnstew
  Instagram: http://instagram.com/j0hnstew


# Info
archive_footer_content: Don't think, just do.
post_footer_content: Move fast, break shit.
