# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: John Stewart
description: Lorem ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Aliquam eleifend dolor vitae [libero pharetra](http://hexo.io) adipiscing. Etiam adipiscing dolor a quam tempor, eu convallis nulla varius. Aliquam sollicitudin risus a porta aliquam.
links:
  Blog: /archives
  GitHub: https://github.com/johnstew
  Twitter: http://twitter.com/j0hnstew
  Codepen: http://codepen.io/johnstew
  Instagram: http://instagram.com/j0hnstew


# Info
archive_footer_content: Don't think, just do.
post_footer_content: Move fast, break shit.
